namespace Forjix.Application.Features.Purchases;
public sealed record SupplierItem(Guid Id,string Name,string? Document,string? Email,string? Phone,string? ContactName,string? Notes,bool IsActive,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt);
public sealed record SaveSupplierRequest(string Name,string? Document,string? Email,string? Phone,string? ContactName,string? Notes,bool IsActive);
public sealed record PagedSuppliers(IReadOnlyList<SupplierItem> Items,int Page,int PageSize,int Total);
public sealed record CreatePurchaseItemRequest(Guid ProductId,decimal Quantity,decimal UnitCost);
public sealed record CreatePurchaseRequest(Guid SupplierId,string? Notes,IReadOnlyList<CreatePurchaseItemRequest> Items);
public sealed record PurchaseItemView(Guid Id,Guid ProductId,string ProductName,string Sku,decimal Quantity,decimal UnitCost,decimal Total);
public sealed record PurchaseView(Guid Id,string Number,Guid SupplierId,string SupplierName,string Status,decimal Total,string? Notes,Guid UserId,string UserName,DateTimeOffset CreatedAt,DateTimeOffset? ReceivedAt,DateTimeOffset? CancelledAt,string RowVersion,IReadOnlyList<PurchaseItemView> Items);
public sealed record PurchaseListItem(Guid Id,string Number,string SupplierName,string Status,decimal Total,int ItemCount,DateTimeOffset CreatedAt,string RowVersion);
public sealed record PagedPurchases(IReadOnlyList<PurchaseListItem> Items,int Page,int PageSize,int Total);
public sealed record PurchaseActionRequest(string RowVersion);
