using System.Net.Mail; using System.Text.Json; using Forjix.Application.Abstractions.Identity; using Forjix.Application.Abstractions.Purchases; using Forjix.Application.Abstractions.Tenancy; using Forjix.Application.Common; using Forjix.Domain.Entities.Audit; using Forjix.Domain.Entities.Purchases; using Forjix.Domain.Enums;
namespace Forjix.Application.Features.Purchases;
internal sealed class PurchaseService(ITenantDatabaseResolver resolver,IPurchaseStoreFactory factory,ICurrentUser current,TimeProvider clock):IPurchaseService {
 public async Task<PagedSuppliers> GetSuppliersAsync(string? search,bool? active,int page,int size,CancellationToken ct=default){page=Math.Max(1,page);size=Math.Clamp(size,1,100);var s=await Store(ct);await using(s){var r=await s.GetSuppliersAsync(Clean(search),active,page,size,ct);return new(r.Item1,page,size,r.Item2);}}
 public async Task<SupplierItem> CreateSupplierAsync(SaveSupplierRequest request,CancellationToken ct=default){var d=ValidateSupplier(request);var s=await Store(ct);await using(s){if(d.Document is not null&&await s.SupplierDocumentExistsAsync(d.Document,null,ct))throw new ResourceConflictException("Documento já cadastrado.");var now=clock.GetUtcNow();var e=new Supplier{Id=Guid.NewGuid(),Name=d.Name,Document=d.Document,Email=d.Email,Phone=d.Phone,ContactName=d.Contact,Notes=d.Notes,IsActive=request.IsActive,CreatedAt=now,UpdatedAt=now};return await s.SaveSupplierAsync(e,Audit(AuditAction.SupplierCreated,e.Id,new{e.Name,e.Document},now),ct);}}
 public async Task<SupplierItem> UpdateSupplierAsync(Guid id,SaveSupplierRequest request,CancellationToken ct=default){var d=ValidateSupplier(request);var s=await Store(ct);await using(s){var e=await s.FindSupplierAsync(id,ct)??throw new ResourceNotFoundException("Fornecedor não encontrado.");if(d.Document is not null&&await s.SupplierDocumentExistsAsync(d.Document,id,ct))throw new ResourceConflictException("Documento já cadastrado.");e.Name=d.Name;e.Document=d.Document;e.Email=d.Email;e.Phone=d.Phone;e.ContactName=d.Contact;e.Notes=d.Notes;e.IsActive=request.IsActive;e.UpdatedAt=clock.GetUtcNow();return await s.SaveSupplierAsync(e,Audit(AuditAction.SupplierUpdated,e.Id,new{e.Name,e.IsActive},e.UpdatedAt),ct);}}
 public async Task<PagedPurchases> GetPurchasesAsync(string? search,string? status,int page,int size,CancellationToken ct=default){PurchaseStatus? parsed=null;if(!string.IsNullOrWhiteSpace(status)){if(!Enum.TryParse<PurchaseStatus>(status,true,out var p))throw new RequestValidationException("Status inválido.");parsed=p;}page=Math.Max(1,page);size=Math.Clamp(size,1,100);var s=await Store(ct);await using(s){var r=await s.GetPurchasesAsync(Clean(search),parsed,page,size,ct);return new(r.Item1,page,size,r.Item2);}}
 public async Task<PurchaseView> GetPurchaseAsync(Guid id,CancellationToken ct=default){var s=await Store(ct);await using(s)return await s.GetPurchaseAsync(id,ct)??throw new ResourceNotFoundException("Compra não encontrada.");}
 public async Task<PurchaseView> CreatePurchaseAsync(CreatePurchaseRequest request,CancellationToken ct=default){if(request.SupplierId==Guid.Empty||request.Items.Count==0||request.Items.Any(x=>x.ProductId==Guid.Empty||x.Quantity<=0||x.UnitCost<0))throw new RequestValidationException("Informe fornecedor e itens válidos.");var s=await Store(ct);await using(s)return await s.CreatePurchaseAsync(User(),request,clock.GetUtcNow(),Ctx(),ct);}
 public async Task<PurchaseView> ReceiveAsync(Guid id,PurchaseActionRequest request,CancellationToken ct=default){var s=await Store(ct);await using(s)return await s.ReceiveAsync(id,User(),Version(request.RowVersion),clock.GetUtcNow(),Ctx(),ct);}
 public async Task<PurchaseView> CancelAsync(Guid id,PurchaseActionRequest request,CancellationToken ct=default){var s=await Store(ct);await using(s)return await s.CancelAsync(id,User(),Version(request.RowVersion),clock.GetUtcNow(),Ctx(),ct);}
 private async Task<IPurchaseStore> Store(CancellationToken ct){if(current.TenantId is not{} id)throw new ResourceNotFoundException("Tenant não encontrado.");return factory.Create(await resolver.ResolveByTenantIdAsync(id,ct)??throw new ResourceNotFoundException("Tenant não encontrado."));} private Guid User()=>current.UserId??throw new ResourceNotFoundException("Usuário não encontrado."); private Forjix.Application.Abstractions.Sales.SalesAuditContext Ctx()=>new(current.CorrelationId,current.IpAddress); private AuditLog Audit(AuditAction action,Guid id,object data,DateTimeOffset now)=>new(){UserId=current.UserId,Action=action,EntityName=nameof(Supplier),EntityId=id.ToString(),AfterData=JsonSerializer.Serialize(data),CorrelationId=current.CorrelationId,IpAddress=current.IpAddress,OccurredAt=now};
 private static byte[] Version(string value){try{var v=Convert.FromBase64String(value);if(v.Length==0)throw new FormatException();return v;}catch(FormatException){throw new RequestValidationException("Versão do registro inválida.");}} private static (string Name,string? Document,string? Email,string? Phone,string? Contact,string? Notes) ValidateSupplier(SaveSupplierRequest r){var n=Clean(r.Name);if(n is null||n.Length>160)throw new RequestValidationException("Nome inválido.");var d=Clean(r.Document);if(d is not null){d=new string(d.Where(char.IsDigit).ToArray());if(d.Length is not(11 or 14))throw new RequestValidationException("Documento inválido.");}var e=Clean(r.Email);if(e is not null)try{_=new MailAddress(e);}catch(FormatException){throw new RequestValidationException("E-mail inválido.");}return(n,d,e,Clean(r.Phone),Clean(r.ContactName),Clean(r.Notes));} private static string? Clean(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim(); }
